name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx for building multi-platform images if needed
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Build and start the services
      - name: Build and run services
        run: |
          docker-compose -f docker-compose.yml up -d --build

      # Check service status
      - name: Check service status
        run: |
          docker-compose ps

      # Stop and clean up services
      - name: Stop services
        run: |
          docker-compose down --volumes